[project]
name = "budget-tool"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "currencies>=2020.12.12",
    "email-validator>=2.2.0",
    "phonenumbers>=9.0.10",
]
